collectr/ingest/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.LinkView.as_view(), name="links"),
]

collectr/link_tracking/urls.py
# django
from django.conf.urls import url

# localapp
from . import views

urlpatterns = [
    url(r'^l/(?P<link_id>\d+)/$', views.track_link, name="track_link"),
]

collectr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'collectr.views.home', name='home'),
    # url(r'^collectr/', include('collectr.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('collectr.webfront.urls', namespace='webfront')),
    url(r'', include('collectr.link_tracking.urls', namespace='link_tracking')),
    url(r'^collector/', include('collectr.collector.urls', namespace='collector')),
    url(r'^profile/', include('collectr.userprofile.urls', namespace='userprofile')),
    url(r'^api/', include('collectr.webapi.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

collectr/webapi/urls.py
# django
from django.conf.urls import include, url

from tastypie.api import Api

from collectr.webapi import api

v1_api = Api(api_name='1.0')
v1_api.register(api.LinkSumResource())
v1_api.register(api.UrlResource())
v1_api.register(api.RssResource())
v1_api.register(api.CollectionResource())
v1_api.register(api.SourceResource())
v1_api.register(api.UserResource())


urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

collectr/webfront/urls.py
# django
from django.conf.urls import url
from django.contrib.auth.views import login

# localapp
from collectr.webfront import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^search/$', views.SearchView.as_view(), name="search"),
    url(r'^login/$', login, {'template_name': 'webfront/login.html'}, name="login"),
    url(r'^logout/$', login, name="logout"),
    url(r'^links/(?P<period>today|yesterday|(this|last)_(week|month))/$', views.DateView.as_view(), name="links_today"),
    url(r'^collection/$', views.CollectionView.as_view(), name="collection"),
    url(r'^collection/(?P<collection>\w+)/$', views.CollectionView.as_view(), name="collection"),
    url(r'^collection/source/(?P<source>\w+)/$', views.SourceView.as_view(), name="collection_source"),
    url(r'^collection/tag/(?P<tag>.*)/$', views.CollectionTagView.as_view(), name="collection_tag"),
    url(r'^collection/user/(?P<user>.*)/(?P<source>\w+)/$', views.CollectionUserView.as_view(), name="collection_user"),
]

collectr/link_tracking/models.py
from django.db import models

# Create your models here.

collectr/semantism/models.py
"""Empty models.py"""

collectr/userprofile/forms.py
# python
from itertools import chain

# django
from django import forms
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape
from django.utils.safestring import mark_safe

# source

from collectr.source import models as source_models


class TableCheckboxSelectMultiple(forms.SelectMultiple):

    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)
        output = [u'']
        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])
        for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
            # If an ID attribute was given, add a numeric index as a suffix,
            # so that the checkboxes don't all have the same ID attribute.
            if has_id:
                final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
                label_for = u' for="%s"' % final_attrs['id']
            else:
                label_for = ''

            cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_unicode(option_value)
            rendered_cb = cb.render(name, option_value)
            option_label = conditional_escape(force_unicode(option_label))
            output.append(u'<tr><td><label%s>%s</label></td><td>%s</td></tr>' % (label_for, option_label, rendered_cb))
        output.append(u'')
        return mark_safe(u'\n'.join(output))

    def id_for_label(self, id_):
        # See the comment for RadioSelect.id_for_label()
        if id_:
            id_ += '_0'
        return id_


class FiltersForm(forms.Form):
    filters = forms.ModelMultipleChoiceField(queryset=source_models.Filter.objects.all(),
        widget=TableCheckboxSelectMultiple)

    def __init__(self, user, *args, **kwargs):
        super(FiltersForm, self).__init__(*args, **kwargs)
        self.fields['filters'].queryset = self.fields['filters'].queryset.filter(user=user)


class RssForm(forms.Form):
    feeds = forms.ModelMultipleChoiceField(queryset=source_models.Rss.objects.all(),
        widget=TableCheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(RssForm, self).__init__(*args, **kwargs)
        self.fields['feeds'].initial = source_models.Rss.objects.filter(users=user)


class AddRssForm(forms.ModelForm):

    class Meta:
        model = source_models.Rss
        fields = ['link', 'name']

collectr/collector/views.py
# python
from datetime import datetime

# django
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.views.generic import TemplateView

# rq
from redis import Redis
from rq import Queue, Connection

from collectr.semantism.process import index_url


class AcceptTemplateResponse(TemplateResponse):
    """`TemplateResponse` that returns with 202 Accept status code."""
    status_code = 202


class SubmitBookmarkView(TemplateView):

    response_class = AcceptTemplateResponse
    template_name = 'collector/bookmark_submit.html'

    def get(self, request, *args, **kwargs):
        url = request.GET.get('url')
        link_from = request.GET.get('from')
        source = request.GET.get('source')
        token = request.GET.get('token')

        if None in (url, link_from, source, token):
            return HttpResponse(status=400)

        try:
            user = User.objects.get(username=kwargs['username'],
                                    userprofile__token=token)
        except User.DoesNotExist:
            return HttpResponse(status=403)

        with Connection(Redis(**settings.RQ_DATABASE)):
            links_queue = Queue('link_indexing')
            links_queue.enqueue_call(
                func=index_url,
                args=(url, user.id, datetime.now(), link_from, source),
                timeout=60
            )

        return super(SubmitBookmarkView, self).get(request, *args, **kwargs)

collectr/ingest/views.py
from django.views.generic.list import ListView

from . import models


class LinkView(ListView):

    template_name = 'ingest/link_list.html'
    model = models.Link
    ordering = ['-processed_at']

    def get_queryset(self):
        queryset = super(LinkView, self).get_queryset()
        return queryset.select_related(
            'link', 'sharer', 'sharer__media'
        ).filter(
            processed_at__isnull=False,
            metadata__user=self.request.user,
        )

collectr/link_tracking/views.py
# Create your views here.
from django.shortcuts import redirect

from collectr.source.models import LinkSum, UrlViews


def track_link(request, link_id):
    link = LinkSum.objects.select_related('url__link').get(pk=link_id)
    link.read = True
    link.save()

    try:
        uv = UrlViews.objects.get(url__linksum__pk=link.pk)
        uv.count += 1
        uv.save()
    except UrlViews.DoesNotExist:
        url = link.url
        uv = UrlViews.objects.create(count=1)
        url.views = uv
        url.save()

    return redirect(link.url.link)

collectr/source/views.py
# Create your views here.

collectr/userprofile/views.py
# django
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, FormView

from . import forms


class LoginRequiredMixin(object):
    """User must be logged in to access this view."""

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


@login_required
def home(request):
    return render(request, 'userprofile/home.html')


class SelectRSSView(LoginRequiredMixin, FormView):

    form_class = forms.RssForm
    template_name = 'userprofile/rss.html'

    def get_success_url(self):
        return reverse('userprofile:rss')

    def get_form_kwargs(self):
        kwargs = super(SelectRSSView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        to_add = form.cleaned_data['feeds']
        to_del = list(set(form.fields['feeds'].initial) - set(to_add))

        for feed in to_add:
            feed.users.add(self.request.user)

        for feed in to_del:
            feed.users.remove(self.request.user)

        super(SelectRSSView, self).form_valid(self, form)


class AddRSSView(LoginRequiredMixin, CreateView):

    form_class = forms.AddRssForm
    template_name = 'userprofile/add_rss.html'

    def get_success_url(self):
        return reverse('userprofile:rss')


@login_required
def filters(request):

    form = forms.FiltersForm(request.user, data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        for filtr in forms.filters:
            pass
        return redirect('userprofile:home')

    data = {
        'form': form,
    }
    return render(request, 'userprofile/filters.html', data)

collectr/webfront/views.py
# python
from datetime import datetime
from dateutil.relativedelta import relativedelta

# django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, TemplateView

# collector
from collectr.source.models import LinkSum, Collection, Source


def home(request, template="webfront/home.html"):
    data = {
    }
    if request.user.is_authenticated():
        return redirect("webfront:collection")
    return render(request, template, data)


def get_display_paginate_item(paginator, page, adjacent_pages=5):
    """Alternate list of pages for paginated view.

    Prepares a compact list of pages including first and last page as well as
    a `adjacent_pages` number of pages around current `page`.
    """
    total_page = paginator.num_pages

    # Not enough pages
    if total_page <= adjacent_pages:
        page_range = paginator.page_range

    # first pages
    elif page <= 2 * (adjacent_pages / 2):
        page_range = range(1, adjacent_pages + 1)
        page_range.extend(['...', total_page])

    # between
    elif page <= total_page - 2 * (adjacent_pages / 2) :
        page_range = [1, '...']
        page_range.extend(range(
            page - adjacent_pages / 2,
            page + adjacent_pages / 2 + 1
        ))
        page_range.extend(['...', total_page])

    # last pages
    elif page > total_page - 2 * (adjacent_pages / 2):
        page_range = [1, '...']
        page_range.extend(range(
            total_page - adjacent_pages + 1,
            total_page + 1
        ))

    else:
        page_range = []

    return page_range


class BaseLinkSumView(ListView):
    """Basic view listing `LinkSum` objects."""

    template_name = 'webfront/collection.html'
    context_object_name = 'links'
    model = LinkSum
    ordering = ['-pk']
    paginate_by = 42

    def get_queryset(self):
        queryset = super(BaseLinkSumView, self).get_queryset()

        self.user_collections = Collection.objects.filter(
            Q(user__id=self.request.user.id) | Q(user__isnull=True)
        )

        return queryset \
            .filter(user=self.request.user) \
            .filter(hidden=False) \
            .prefetch_related('authors')

    def get_context_data(self, **kwargs):
        # TODO: handle filter on read/unread/all
        context = {
            'collections': self.user_collections,
            'sources': Source.objects.all(),
        }
        context.update(kwargs)

        # Ask parent about pagination context
        context = super(BaseLinkSumView, self).get_context_data(**context)

        # Insert our custom compact pagination
        context.update({'page_range': get_display_paginate_item(
            context['paginator'], context['page_obj']
        )})
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BaseLinkSumView, self).dispatch(*args, **kwargs)


class SearchView(TemplateView):
    # XXX: cannot paginate RawQuerySet
    template_name = 'webfront/collection.html'

    def get_queryset(self):
        return LinkSum.objects.raw("""
            SELECT
                DISTINCT "source_linksum"."id", "source_linksum"."url_id",
                "source_linksum"."read", "source_linksum"."recommanded",
                "source_linksum"."collection_id",
                "source_linksum"."inserted_at", "source_linksum"."user_id"
            FROM source_linksum
            INNER JOIN source_url ON
                (source_linksum.url_id = source_url.id)
            AND
                to_tsvector('english', source_url.content) @@ to_tsquery('english', %s)
            AND "source_linksum"."user_id" = %s
            AND "source_linksum"."hidden" IS False
            ORDER BY "source_linksum"."inserted_at" DESC;
        """, [self.querystring, self.request.user.id])

    def get_context_data(self, **kwargs):
        context = {
            'links': self.object_list,
            'query': self.querystring,
            'collections': Collection.objects.filter(
                Q(user__id=self.request.user.id) | Q(user__isnull=True)
            ),
            'sources': Source.objects.all(),
        }
        context.update(kwargs)
        return super(SearchView, self).get_context_data(**context)

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        querystring = request.GET.get('query')
        if not querystring:
            messages.error(request, u"Please enter a valid search term")
            return redirect('webfront:home')

        self.querystring = querystring.replace(' ', ' & ')
        self.object_list = self.get_queryset()
        return super(SearchView, self).get(request, *args, **kwargs)


class CollectionMixin(object):
    """Add per-collection filtering."""

    def get_queryset(self):
        queryset = super(CollectionMixin, self).get_queryset()

        collection = self.kwargs.get('collection', 'unread')
        if collection == 'unread':
            collection = 'all'

        return queryset.filter(
            collection=self.user_collections.filter(name__iexact=collection)
        )


class DateView(CollectionMixin, BaseLinkSumView):

    ordering = ['-recommanded']

    def get_queryset(self):
        queryset = super(DateView, self).get_queryset()

        now = datetime.now()
        today = datetime(now.year, now.month, now.day)
        period_start, period_end = {
            'today': (today, now),
            'yesterday': (today + relativedelta(days=-1), today),
            'this_week': (today + relativedelta(weeks=-1, weekday=0), now),
            'last_week': (today + relativedelta(weeks=-2, weekday=0),
                          today + relativedelta(weeks=-1, weekday=0)),
            'this_month': (today + relativedelta(day=1), now),
            'last_month': (today + relativedelta(day=1, months=-1),
                           today + relativedelta(day=1)),
        }[self.kwargs.get('period', 'today')]

        return queryset.filter(inserted_at__range=(period_start, period_end))


class SourceView(BaseLinkSumView):

    def get_queryset(self):
        queryset = super(SourceView, self).get_queryset()
        return queryset.filter(
            sources__slug=self.kwargs.get('source'),
        )


class CollectionView(CollectionMixin, BaseLinkSumView):
    pass


class CollectionTagView(BaseLinkSumView):

    def get_queryset(self):
        queryset = super(CollectionTagView, self).get_queryset()
        return queryset.filter(
            url__tags__name=self.kwargs.get('tag'),
        )


class CollectionUserView(BaseLinkSumView):

    def get_queryset(self):
        queryset = super(CollectionUserView, self).get_queryset()
        return queryset.filter(
            authors__name=self.kwargs.get('user'),
            authors__source__slug=self.kwargs.get('source'),
        )


@login_required
def ajax_hide_linksum(request, linksum_id):
    if not request.is_ajax():
        return HttpResponse(status_code=400)

    link = get_object_or_404(LinkSum, pk=linksum_id, user_id=request.user.pk)
    link.hidden = True
    link.save()

collectr/templates/webfront/collection.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} - Your links{% endblock title %}

{% block sidebar %}
<div class="panel panel-info">
   <div class="panel-heading">{% trans 'Collections' %}</div>
   <div class="panel-body">
     <ul>
      {% for col in collections %}
      <li><a href="{% url 'webfront:collection' col.name %}">{{ col.name }}</a></li>
      {% endfor %}
     </ul>
   </div>
</div>
<div class="panel panel-info">
   <div class="panel-heading">{% trans 'Sources' %}</div>
    <ul>
    {% for source in sources %}
    <li><a href="{% url 'webfront:collection_source' source.slug %}">{{ source.name }}</a></li>
    {% endfor %}
    </ul>
   </div>
</div><!-- /.panel -->
{% endblock sidebar %}

{% block middle-container %}
    {% for link in links %}
     <h3><a href="{% url 'link_tracking:track_link' link.pk %}" target="_blank">{{ link.url.title }}</a>
      {% if link.read %}
      <i class="icon-search"></i>
      {% else %}
      <i class="icon-envelope"></i>
      {% endif %}
    </h3>
    <p><a href="http://twitter.com/share?url=http://{{ request.META.HTTP_HOST }}{% url 'link_tracking:track_link' link.pk %}&text=&quot;{{link.url.title}}&quot;" target='_blank'>tweet</a></p>
    {% if not link.author_id %}
    {% for author in link.authors.all %}
        <a href="{% url 'webfront:collection_user' author.name author.source_id %}">
            <span class="label label-success">{{ author.name }}</span>
        </a>
    {% endfor %}
    {% else %}
        <a href="{% url 'webfront:collection_user' link.author.name link.author.source_id %}">
            <span class="label label-success">{{ link.author.name }}</span>
        </a>
    {% endif %}
      <p> on {{ link.inserted_at }}</p>
      <p> {% for tag in link.tags.all %}
        <a href="{% url 'webfront:collection_tag' tag %}"><span class="label label-info">{{ tag }}</span></a>
       {% endfor %} </p>
        {% if link.url.html %}
        {{ link.url.html|safe }}
        {% elif link.url.image %}
        <img src="{{ link.url.image }}" />
        {% endif %}
      <p>{{ link.url.summary|safe }}</p>
    {% endfor %}
{% endblock middle-container %}

{% block pagination %}
{% include 'webfront/pagination.html' %}
{% endblock pagination %}

collectr/templates/webfront/home.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} - Home{% endblock title %}

{% block container-fluid %}

<div class="hero-unit">
        <h1>Hello, world!</h1>
        <p>{% blocktrans %}This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.{% endblocktrans %}</p>
        <p><a class="btn btn-primary btn-large">{% trans 'Learn more' %} &raquo;</a></p>
</div>

{% endblock container-fluid %}

collectr/templates/webfront/links_today.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} - Your links{% endblock title %}

{% block sidebar %}
<ul class="nav nav-list">
  <li class="nav-header">{% trans 'Collections' %}</li>
  {% for col in collections %}
  <li><a href="{% url 'webfront:collection' col.name %}">{{ col.name }}</a></li>
  {% endfor %}
</ul>
<ul class="nav nav-list">
  <li class="nav-header">{% trans 'Sources' %}</li>
  {% for source in sources %}
  <li><a href="{% url 'webfront:collection_source' source.slug %}">{{ source.name }}</a></li>
  {% endfor %}
</ul>

{% endblock sidebar %}

{% block middle-container %}

      <div class="row-fluid">
{% for link in links %}
        <div class="span6">
            <h3>{{ link.title }}
              {% if link.read %}
              <i class="icon-search"></i>
              {% else %}
              <i class="icon-envelope"></i>
              {% endif %}
            </h3>
            {% if not link.author_id %}
            {% for author in link.authors.all %}
                <a href="{% url 'webfront:collection_user' author.name, author.source_id %}">
                    <span class="label label-success">{{ author.name }}</span>
                </a>
            {% endfor %}
            {% else %}
                <a href="{% url 'webfront:collection_user' link.author.name, link.author.source_id %}">
                    <span class="label label-success">{{ link.author.name }}</span>
                </a>
            {% endif %}
          <p> on {{ link.inserted_at }}</p>
          <p> {% for tag in link.get_tags %}
            <a href="{% url 'webfront:collection_tag' tag %}"><span class="label label-info">{{ tag }}</span></a>
           {% endfor %} </p>
            {% if link.url.image %}
            <img src="{{ link.url.image }}" />
            {% endif %}
          {% if not link.summary == "None" %}
          <p>{{ link.summary|safe }}</p>
          {% endif %}
          <p><a class="btn" href="{% url 'link_tracking:track_link' link.pk %}" target="_blank">{% trans 'open link' %} &raquo;</a></p>
        </div><!--/span-->
    {% if forloop.counter|divisibleby:"2" %}
    </div><!--/row-->
    <div class="row-fluid">
    {% endif %}
{% endfor %}

<br />
<br />


{% endblock middle-container %}



{% block pagination %}

<div class="pagination">
  <ul>
    {% if paginator.has_previous %}
    <li class="previous"><a href="?page={{ paginator.previous_page_number }}">{% trans "Previous" %}</a>
    {% else %}
    <li class="previous disabled"><a href="?page={{ paginator.previous_page_number }}">{% trans "Previous" %}</a>

    {% endif %}
    {% for page_num in page_range %}
    {% if page_num == "..." %}
    <li class="disabled"><a href="?page={{ page_num}}">{{ page_num }}</a>
    {% else %}
    <li><a href="?page={{ page_num}}">{{ page_num }}</a>
    {% endif %}
    {% endfor %}
    {% if paginator.has_next %}
    <li class="next"><a href="?page={{ paginator.next_page_number }}">{% trans "Next" %}</a>
    {% else %}
    <li class="next disabled"><a href="?page={{ paginator.next_page_number }}">{% trans "Next" %}</a>
    {% endif %}
   
  </ul>
</div>


{% comment %}
{{ page_range|pprint }}
<div class="pager">
  <ul class="pager">
    {% if paginator.has_previous %}
    <li class="previous"><a href="?page={{ paginator.previous_page_number }}">{% trans "Previous" %}</a>
    {% endif %}
    <li class=".disabled"><a href="?page={{ paginator.number }}"> {{ paginator.number }} </a></li>

    {% if paginator.has_next %}
    <li class="next"><a href="?page={{ paginator.next_page_number }}">{% trans "Next" %}</a>
    {% endif %}
  </ul>
</div>
{% endcomment %}
{% endblock pagination %}

collectr/templates/webfront/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} - Home{% endblock title %}

{% block container-fluid %}
<ul>
  {% if 'google-oauth2' in backends.backends %}
  <li>
    <a href="{% url 'social:begin' 'google-oauth2' %}">Enter using Google</a>
  </li>
  {% endif %}
  {% if 'reddit' in backends.backends %}
  <li>
    <a href="{% url 'social:begin' 'reddit' %}">Enter using Reddit</a>
  </li>
  {% endif %}
  {% if 'twitter' in backends.backends %}
  <li>
    <a href="{% url 'social:begin' 'twitter' %}">Enter using Twitter</a>
  </li>
  {% endif %}
</ul>

<form action="" method="post" class="form-horizontal">{% csrf_token %}
    {{ form }}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>


{% endblock container-fluid %}

collectr/templates/webfront/pagination.html
{% load i18n %}

<div class="pagination">
  <ul>
    {% if paginator.has_previous %}
    <li class="previous"><a href="?page={{ paginator.previous_page_number }}">{% trans "Previous" %}</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">{% trans "Previous" %}</a></li>
    {% endif %}

    {% for page_num in page_range %}
    {% if page_num == "..." %}
    <!-- <li class="disabled"></li> -->
    {% elif page_num == paginator.number %}
    <li class="active"><a href="#">{{ page_num }}</a></li>
    {% else %}
    <li><a href="?page={{ page_num}}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}
    
    {% if paginator.has_next %}
    <li class="next"><a href="?page={{ paginator.next_page_number }}">{% trans "Next" %}</a></li>
    {% else %}
    <li class="next disabled"><a href="#">{% trans "Next" %}</a></li>
    {% endif %}
  </ul>
</div>