collectr/ingest/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.LinkView.as_view(), name="links"),
]

collectr/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'collectr.views.home', name='home'),
    # url(r'^collectr/', include('collectr.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('collectr.webfront.urls', namespace='webfront')),
    url(r'', include('collectr.link_tracking.urls', namespace='link_tracking')),
    url(r'^collector/', include('collectr.collector.urls', namespace='collector')),
    url(r'^profile/', include('collectr.userprofile.urls', namespace='userprofile')),
    url(r'^api/', include('collectr.webapi.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

collectr/webapi/urls.py
# django
from django.conf.urls import include, url

from tastypie.api import Api

from collectr.webapi import api

v1_api = Api(api_name='1.0')
v1_api.register(api.LinkSumResource())
v1_api.register(api.UrlResource())
v1_api.register(api.RssResource())
v1_api.register(api.CollectionResource())
v1_api.register(api.SourceResource())
v1_api.register(api.UserResource())


urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

collectr/webfront/urls.py
# django
from django.conf.urls import url
from django.contrib.auth.views import login

# localapp
from collectr.webfront import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^search/$', views.SearchView.as_view(), name="search"),
    url(r'^login/$', login, {'template_name': 'webfront/login.html'}, name="login"),
    url(r'^logout/$', login, name="logout"),
    url(r'^links/(?P<period>today|yesterday|(this|last)_(week|month))/$', views.DateView.as_view(), name="links_today"),
    url(r'^collection/$', views.CollectionView.as_view(), name="collection"),
    url(r'^collection/(?P<collection>\w+)/$', views.CollectionView.as_view(), name="collection"),
    url(r'^collection/source/(?P<source>\w+)/$', views.SourceView.as_view(), name="collection_source"),
    url(r'^collection/tag/(?P<tag>.*)/$', views.CollectionTagView.as_view(), name="collection_tag"),
    url(r'^collection/user/(?P<user>.*)/(?P<source>\w+)/$', views.CollectionUserView.as_view(), name="collection_user"),
]

collectr/link_tracking/models.py
from django.db import models

# Create your models here.

collectr/semantism/models.py
"""Empty models.py"""

collectr/userprofile/forms.py
# python
from itertools import chain

# django
from django import forms
from django.utils.encoding import force_unicode
from django.utils.html import conditional_escape
from django.utils.safestring import mark_safe

# source

from collectr.source import models as source_models


class TableCheckboxSelectMultiple(forms.SelectMultiple):

    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        has_id = attrs and 'id' in attrs
        final_attrs = self.build_attrs(attrs, name=name)
        output = [u'']
        # Normalize to strings
        str_values = set([force_unicode(v) for v in value])
        for i, (option_value, option_label) in enumerate(chain(self.choices, choices)):
            # If an ID attribute was given, add a numeric index as a suffix,
            # so that the checkboxes don't all have the same ID attribute.
            if has_id:
                final_attrs = dict(final_attrs, id='%s_%s' % (attrs['id'], i))
                label_for = u' for="%s"' % final_attrs['id']
            else:
                label_for = ''

            cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_unicode(option_value)
            rendered_cb = cb.render(name, option_value)
            option_label = conditional_escape(force_unicode(option_label))
            output.append(u'<tr><td><label%s>%s</label></td><td>%s</td></tr>' % (label_for, option_label, rendered_cb))
        output.append(u'')
        return mark_safe(u'\n'.join(output))

    def id_for_label(self, id_):
        # See the comment for RadioSelect.id_for_label()
        if id_:
            id_ += '_0'
        return id_


class FiltersForm(forms.Form):
    filters = forms.ModelMultipleChoiceField(queryset=source_models.Filter.objects.all(),
        widget=TableCheckboxSelectMultiple)

    def __init__(self, user, *args, **kwargs):
        super(FiltersForm, self).__init__(*args, **kwargs)
        self.fields['filters'].queryset = self.fields['filters'].queryset.filter(user=user)


class RssForm(forms.Form):
    feeds = forms.ModelMultipleChoiceField(queryset=source_models.Rss.objects.all(),
        widget=TableCheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(RssForm, self).__init__(*args, **kwargs)
        self.fields['feeds'].initial = source_models.Rss.objects.filter(users=user)


class AddRssForm(forms.ModelForm):

    class Meta:
        model = source_models.Rss
        fields = ['link', 'name']

collectr/collector/views.py
# python
from datetime import datetime

# django
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.views.generic import TemplateView

# rq
from redis import Redis
from rq import Queue, Connection

from collectr.semantism.process import index_url


class AcceptTemplateResponse(TemplateResponse):
    """`TemplateResponse` that returns with 202 Accept status code."""
    status_code = 202


class SubmitBookmarkView(TemplateView):

    response_class = AcceptTemplateResponse
    template_name = 'collector/bookmark_submit.html'

    def get(self, request, *args, **kwargs):
        url = request.GET.get('url')
        link_from = request.GET.get('from')
        source = request.GET.get('source')
        token = request.GET.get('token')

        if None in (url, link_from, source, token):
            return HttpResponse(status=400)

        try:
            user = User.objects.get(username=kwargs['username'],
                                    userprofile__token=token)
        except User.DoesNotExist:
            return HttpResponse(status=403)

        with Connection(Redis(**settings.RQ_DATABASE)):
            links_queue = Queue('link_indexing')
            links_queue.enqueue_call(
                func=index_url,
                args=(url, user.id, datetime.now(), link_from, source),
                timeout=60
            )

        return super(SubmitBookmarkView, self).get(request, *args, **kwargs)

collectr/ingest/views.py
from django.views.generic.list import ListView

from . import models


class LinkView(ListView):

    template_name = 'ingest/link_list.html'
    model = models.Link
    ordering = ['-processed_at']

    def get_queryset(self):
        queryset = super(LinkView, self).get_queryset()
        return queryset.select_related(
            'link', 'sharer', 'sharer__media'
        ).filter(
            processed_at__isnull=False,
            metadata__user=self.request.user,
        )

collectr/link_tracking/views.py
# Create your views here.
from django.shortcuts import redirect

from collectr.source.models import LinkSum, UrlViews


def track_link(request, link_id):
    link = LinkSum.objects.select_related('url__link').get(pk=link_id)
    link.read = True
    link.save()

    try:
        uv = UrlViews.objects.get(url__linksum__pk=link.pk)
        uv.count += 1
        uv.save()
    except UrlViews.DoesNotExist:
        url = link.url
        uv = UrlViews.objects.create(count=1)
        url.views = uv
        url.save()

    return redirect(link.url.link)

collectr/source/views.py
# Create your views here.

collectr/userprofile/views.py
# django
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, FormView

from . import forms


class LoginRequiredMixin(object):
    """User must be logged in to access this view."""

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


@login_required
def home(request):
    return render(request, 'userprofile/home.html')


class SelectRSSView(LoginRequiredMixin, FormView):

    form_class = forms.RssForm
    template_name = 'userprofile/rss.html'

    def get_success_url(self):
        return reverse('userprofile:rss')

    def get_form_kwargs(self):
        kwargs = super(SelectRSSView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        to_add = form.cleaned_data['feeds']
        to_del = list(set(form.fields['feeds'].initial) - set(to_add))

        for feed in to_add:
            feed.users.add(self.request.user)

        for feed in to_del:
            feed.users.remove(self.request.user)

        super(SelectRSSView, self).form_valid(self, form)


class AddRSSView(LoginRequiredMixin, CreateView):

    form_class = forms.AddRssForm
    template_name = 'userprofile/add_rss.html'

    def get_success_url(self):
        return reverse('userprofile:rss')


@login_required
def filters(request):

    form = forms.FiltersForm(request.user, data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        for filtr in forms.filters:
            pass
        return redirect('userprofile:home')

    data = {
        'form': form,
    }
    return render(request, 'userprofile/filters.html', data)

collectr/webfront/views.py
# python
from datetime import datetime
from dateutil.relativedelta import relativedelta

# django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, TemplateView

# collector
from collectr.source.models import LinkSum, Collection, Source


def home(request, template="webfront/home.html"):
    data = {
    }
    if request.user.is_authenticated():
        return redirect("webfront:collection")
    return render(request, template, data)


def get_display_paginate_item(paginator, page, adjacent_pages=5):
    """Alternate list of pages for paginated view.

    Prepares a compact list of pages including first and last page as well as
    a `adjacent_pages` number of pages around current `page`.
    """
    total_page = paginator.num_pages

    # Not enough pages
    if total_page <= adjacent_pages:
        page_range = paginator.page_range

    # first pages
    elif page <= 2 * (adjacent_pages / 2):
        page_range = range(1, adjacent_pages + 1)
        page_range.extend(['...', total_page])

    # between
    elif page <= total_page - 2 * (adjacent_pages / 2) :
        page_range = [1, '...']
        page_range.extend(range(
            page - adjacent_pages / 2,
            page + adjacent_pages / 2 + 1
        ))
        page_range.extend(['...', total_page])

    # last pages
    elif page > total_page - 2 * (adjacent_pages / 2):
        page_range = [1, '...']
        page_range.extend(range(
            total_page - adjacent_pages + 1,
            total_page + 1
        ))

    else:
        page_range = []

    return page_range


class BaseLinkSumView(ListView):
    """Basic view listing `LinkSum` objects."""

    template_name = 'webfront/collection.html'
    context_object_name = 'links'
    model = LinkSum
    ordering = ['-pk']
    paginate_by = 42

    def get_queryset(self):
        queryset = super(BaseLinkSumView, self).get_queryset()

        self.user_collections = Collection.objects.filter(
            Q(user__id=self.request.user.id) | Q(user__isnull=True)
        )

        return queryset \
            .filter(user=self.request.user) \
            .filter(hidden=False) \
            .prefetch_related('authors')

    def get_context_data(self, **kwargs):
        # TODO: handle filter on read/unread/all
        context = {
            'collections': self.user_collections,
            'sources': Source.objects.all(),
        }
        context.update(kwargs)

        # Ask parent about pagination context
        context = super(BaseLinkSumView, self).get_context_data(**context)

        # Insert our custom compact pagination
        context.update({'page_range': get_display_paginate_item(
            context['paginator'], context['page_obj']
        )})
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BaseLinkSumView, self).dispatch(*args, **kwargs)


class SearchView(TemplateView):
    # XXX: cannot paginate RawQuerySet
    template_name = 'webfront/collection.html'

    def get_queryset(self):
        return LinkSum.objects.raw("""
            SELECT
                DISTINCT "source_linksum"."id", "source_linksum"."url_id",
                "source_linksum"."read", "source_linksum"."recommanded",
                "source_linksum"."collection_id",
                "source_linksum"."inserted_at", "source_linksum"."user_id"
            FROM source_linksum
            INNER JOIN source_url ON
                (source_linksum.url_id = source_url.id)
            AND
                to_tsvector('english', source_url.content) @@ to_tsquery('english', %s)
            AND "source_linksum"."user_id" = %s
            AND "source_linksum"."hidden" IS False
            ORDER BY "source_linksum"."inserted_at" DESC;
        """, [self.querystring, self.request.user.id])

    def get_context_data(self, **kwargs):
        context = {
            'links': self.object_list,
            'query': self.querystring,
            'collections': Collection.objects.filter(
                Q(user__id=self.request.user.id) | Q(user__isnull=True)
            ),
            'sources': Source.objects.all(),
        }
        context.update(kwargs)
        return super(SearchView, self).get_context_data(**context)

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        querystring = request.GET.get('query')
        if not querystring:
            messages.error(request, u"Please enter a valid search term")
            return redirect('webfront:home')

        self.querystring = querystring.replace(' ', ' & ')
        self.object_list = self.get_queryset()
        return super(SearchView, self).get(request, *args, **kwargs)


class CollectionMixin(object):
    """Add per-collection filtering."""

    def get_queryset(self):
        queryset = super(CollectionMixin, self).get_queryset()

        collection = self.kwargs.get('collection', 'unread')
        if collection == 'unread':
            collection = 'all'

        return queryset.filter(
            collection=self.user_collections.filter(name__iexact=collection)
        )


class DateView(CollectionMixin, BaseLinkSumView):

    ordering = ['-recommanded']

    def get_queryset(self):
        queryset = super(DateView, self).get_queryset()

        now = datetime.now()
        today = datetime(now.year, now.month, now.day)
        period_start, period_end = {
            'today': (today, now),
            'yesterday': (today + relativedelta(days=-1), today),
            'this_week': (today + relativedelta(weeks=-1, weekday=0), now),
            'last_week': (today + relativedelta(weeks=-2, weekday=0),
                          today + relativedelta(weeks=-1, weekday=0)),
            'this_month': (today + relativedelta(day=1), now),
            'last_month': (today + relativedelta(day=1, months=-1),
                           today + relativedelta(day=1)),
        }[self.kwargs.get('period', 'today')]

        return queryset.filter(inserted_at__range=(period_start, period_end))


class SourceView(BaseLinkSumView):

    def get_queryset(self):
        queryset = super(SourceView, self).get_queryset()
        return queryset.filter(
            sources__slug=self.kwargs.get('source'),
        )


class CollectionView(CollectionMixin, BaseLinkSumView):
    pass


class CollectionTagView(BaseLinkSumView):

    def get_queryset(self):
        queryset = super(CollectionTagView, self).get_queryset()
        return queryset.filter(
            url__tags__name=self.kwargs.get('tag'),
        )


class CollectionUserView(BaseLinkSumView):

    def get_queryset(self):
        queryset = super(CollectionUserView, self).get_queryset()
        return queryset.filter(
            authors__name=self.kwargs.get('user'),
            authors__source__slug=self.kwargs.get('source'),
        )


@login_required
def ajax_hide_linksum(request, linksum_id):
    if not request.is_ajax():
        return HttpResponse(status_code=400)

    link = get_object_or_404(LinkSum, pk=linksum_id, user_id=request.user.pk)
    link.hidden = True
    link.save()

collectr/templates/base.html
{% load i18n staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <link rel="apple-touch-icon" href="{% static "img/favicon.png" %}">

    <title>Linkuist{% block title%}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">

    <style type="text/css">
      body {
        padding-top: 50px;
      }
        .starter-template {
        padding: 40px 15px;
        text-align: center;
      }
    </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">{% trans "Collapse navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Search</span>
                    <span class="glyphicon glyphicon-search"></span>
                </button>
                <a class="navbar-brand" href="{% url 'webfront:home' %}">Linkuist</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                    <li class="active"><a href="{% url 'webfront:login' %}">{% trans 'login' %}</a></li>
                    {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'userprofile:home' %}">{% trans 'Profile' %}</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'webfront:logout' %}">{% trans 'Logout' %}</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>

                <form class="navbar-form navbar-right" action="{% url 'webfront:search' %}" role="search">
                    <div class="input-group">
                        <input name="query" type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button type="reset" class="btn btn-default">
                                <span class="glyphicon glyphicon-remove">
                                    <span class="sr-only">Close</span>
                                </span>
                            </button>
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search">
                                    <span class="sr-only">Search</span>
                                </span>
                            </button>
                        </span>
                    </div>
                </form>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


    <div class="container-fluid">
    {% block container-fluid %}
    <div class="row-fluid">
      <div class="col-md-2">
          {% block sidebar %}
          {% endblock sidebar %}
      </div><!-- /.col-md-2 -->
      <div class="col-md-10">
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
            {% endfor %}
          {% endif %}
          {% block middle-container %}
          {% endblock middle-container %}
      </div><!-- /.col-md-9 -->
    </div><!-- /.row-fluid -->
    {% endblock container-fluid %}
    </div><!-- /.container-fluid -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "jquery/dist/jquery.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap.js" %}"></script>
  </body>
</html>


{% comment %}
{% load i18n staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Linkuist{% block title%}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="apple-mobile-web-app-capable" content="yes" />  
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

    <link rel="apple-touch-icon" href="{% static "img/favicon.png" %}" />
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" />
    <!-- Le styles -->
    <link href="{% static "css/bootstrap.css" rel="stylesheet" %}">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="{% static "css/bootstrap-responsive.css" rel="stylesheet" %}">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{% static "ico/favicon.ico" %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "ico/apple-touch-icon-57-precomposed.png" %}">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url 'webfront:home' %}">Linkuist</a>
          <form class="navbar-search pull-left" action="{% url 'webfront:search' %}">
            <input name="query" type="text" class="search-query span2" placeholder="Search">
          </form>
          <div class="btn-group pull-right">
            {% if not user.is_authenticated %}
            <ul class="nav">
                <li class="active"><a href="{% url 'webfront:login' %}">{% trans 'login' %}</a></li>
            </ul>
            {% else %}
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> {{ user.username }}
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'userprofile:home' %}">Profile</a></li>
              <li class="divider"></li>
              <li><a href="{% url 'webfront:logout' %}">Sign Out</a></li>
          </ul>
            {% endif %}
          </div>
          <div class="nav-collapse">
            <ul class="nav">
                <li class="active"><a href="#">{% trans 'Home' %}</a></li>
                <li><a href="#about">{% trans 'About' %}</a></li>
                <li><a href="#contact">{% trans 'Contact' %}</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      {% block container-fluid %}
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            {% block sidebar %}
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          {% endblock sidebar %}
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
            {% endfor %}
          {% endif %}
          {% block middle-container %}
          <div class="hero-unit">
            <h1>Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
          </div>
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
          {% endblock middle-container %}
        </div><!--/span-->
        {% endblock container-fluid %}

        {% block pagination %} {% endblock pagination %}
      </div><!--/row-->



    </div><!--/.fluid-container-->
      <hr>
      <footer>
        <p>&copy; Benoit Calvez 2012</p>
      </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "jquery/js/jquery.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-transition.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-alert.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-modal.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-dropdown.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-scrollspy.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-tab.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-tooltip.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-popover.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-button.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-collapse.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-carousel.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap-typeahead.js" %}"></script>

  </body>
</html>
{% endcomment %}